name: librewolf
version: 
grade: stable
architectures:
  - build-on: amd64
    build-for: amd64
summary: A custom version of Firefox, focused on privacy, security and freedom.
description: |
  A custom version of Firefox, focused on privacy, security and freedom
  designed to increase protection against tracking and fingerprinting techniques, 
  while also including a few security improvements.
confinement: strict
compression: lzo
base: core22

package-repositories:
  - type: apt
    components: [main]
    suites: [jammy]
    architectures: [amd64]
    key-id: 034F7776EF5E0C613D2F7934D29FBD5F93C0CFC3
    url: https://deb.librewolf.net


apps:
  librewolf:
    command: usr/bin/librewolf
    common-id: io.gitlab.librewolf-community
    desktop: usr/share/applications/librewolf.desktop
    extensions: [gnome]
    plugs:
      - audio-playback
      - audio-record
      - bluez
      - camera
      - cups-control
      - home
      - joystick
      - mount-observe
      - network
      - network-manager
      - opengl
      - password-manager-service
      - pulseaudio
      - raw-usb
      - removable-media
      - screen-inhibit-control
      - u2f-devices
      - upower-observe
    slots:
      - mpris
plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true
  librewolf:
    interface: dbus
    bus: session
    name: io.gitlab.librewolf-community

parts:
  librewolf:
    plugin: nil
    stage-packages:
      - librewolf  
      
